minimumReleaseAge: 0
trustPolicy: no-downgrade
trustPolicyExclude:
  - reselect@5.1.1
  - semver@6.3.1
  - undici-types@6.21.0

allowBuilds:
  esbuild: set this to true or false
  msw: true
  sharp: set this to true or false
ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
