/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HomeRouteImport } from './routes/home'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as NotebooksIndexRouteImport } from './routes/notebooks.index'
import { Route as NotebooksNotebookIdRouteImport } from './routes/notebooks.$notebookId'
import { Route as PrototypeFlashcardsRouteImport } from './routes/prototype.flashcards'
import { Route as PrototypeQuizRouteImport } from './routes/prototype.quiz'
import { Route as PrototypeReportRouteImport } from './routes/prototype.report'
import { Route as PrototypeRoadmapRouteImport } from './routes/prototype.roadmap'
import { Route as PrototypeSlidesRouteImport } from './routes/prototype.slides'
import { Route as PrototypeSourcesWebRouteImport } from './routes/prototype.sources-web'
import { Route as SettingsIndexRouteImport } from './routes/settings.index'
import { Route as SettingsConnectionRouteImport } from './routes/settings.connection'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const NotebooksIndexRoute = NotebooksIndexRouteImport.update({
  id: '/notebooks/',
  path: '/notebooks/',
  getParentRoute: () => rootRouteImport,
} as any)
const NotebooksNotebookIdRoute = NotebooksNotebookIdRouteImport.update({
  id: '/notebooks/$notebookId',
  path: '/notebooks/$notebookId',
  getParentRoute: () => rootRouteImport,
} as any)
const PrototypeFlashcardsRoute = PrototypeFlashcardsRouteImport.update({
  id: '/prototype/flashcards',
  path: '/prototype/flashcards',
  getParentRoute: () => rootRouteImport,
} as any)
const PrototypeQuizRoute = PrototypeQuizRouteImport.update({
  id: '/prototype/quiz',
  path: '/prototype/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const PrototypeReportRoute = PrototypeReportRouteImport.update({
  id: '/prototype/report',
  path: '/prototype/report',
  getParentRoute: () => rootRouteImport,
} as any)
const PrototypeRoadmapRoute = PrototypeRoadmapRouteImport.update({
  id: '/prototype/roadmap',
  path: '/prototype/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const PrototypeSlidesRoute = PrototypeSlidesRouteImport.update({
  id: '/prototype/slides',
  path: '/prototype/slides',
  getParentRoute: () => rootRouteImport,
} as any)
const PrototypeSourcesWebRoute = PrototypeSourcesWebRouteImport.update({
  id: '/prototype/sources-web',
  path: '/prototype/sources-web',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsConnectionRoute = SettingsConnectionRouteImport.update({
  id: '/connection',
  path: '/connection',
  getParentRoute: () => SettingsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRouteWithChildren
  '/notebooks/$notebookId': typeof NotebooksNotebookIdRoute
  '/prototype/flashcards': typeof PrototypeFlashcardsRoute
  '/prototype/quiz': typeof PrototypeQuizRoute
  '/prototype/report': typeof PrototypeReportRoute
  '/prototype/roadmap': typeof PrototypeRoadmapRoute
  '/prototype/slides': typeof PrototypeSlidesRoute
  '/prototype/sources-web': typeof PrototypeSourcesWebRoute
  '/settings/connection': typeof SettingsConnectionRoute
  '/notebooks/': typeof NotebooksIndexRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/notebooks/$notebookId': typeof NotebooksNotebookIdRoute
  '/prototype/flashcards': typeof PrototypeFlashcardsRoute
  '/prototype/quiz': typeof PrototypeQuizRoute
  '/prototype/report': typeof PrototypeReportRoute
  '/prototype/roadmap': typeof PrototypeRoadmapRoute
  '/prototype/slides': typeof PrototypeSlidesRoute
  '/prototype/sources-web': typeof PrototypeSourcesWebRoute
  '/settings/connection': typeof SettingsConnectionRoute
  '/notebooks': typeof NotebooksIndexRoute
  '/settings': typeof SettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRouteWithChildren
  '/notebooks/$notebookId': typeof NotebooksNotebookIdRoute
  '/prototype/flashcards': typeof PrototypeFlashcardsRoute
  '/prototype/quiz': typeof PrototypeQuizRoute
  '/prototype/report': typeof PrototypeReportRoute
  '/prototype/roadmap': typeof PrototypeRoadmapRoute
  '/prototype/slides': typeof PrototypeSlidesRoute
  '/prototype/sources-web': typeof PrototypeSourcesWebRoute
  '/settings/connection': typeof SettingsConnectionRoute
  '/notebooks/': typeof NotebooksIndexRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/home'
    | '/login'
    | '/settings'
    | '/notebooks/$notebookId'
    | '/prototype/flashcards'
    | '/prototype/quiz'
    | '/prototype/report'
    | '/prototype/roadmap'
    | '/prototype/slides'
    | '/prototype/sources-web'
    | '/settings/connection'
    | '/notebooks/'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/home'
    | '/login'
    | '/notebooks/$notebookId'
    | '/prototype/flashcards'
    | '/prototype/quiz'
    | '/prototype/report'
    | '/prototype/roadmap'
    | '/prototype/slides'
    | '/prototype/sources-web'
    | '/settings/connection'
    | '/notebooks'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/home'
    | '/login'
    | '/settings'
    | '/notebooks/$notebookId'
    | '/prototype/flashcards'
    | '/prototype/quiz'
    | '/prototype/report'
    | '/prototype/roadmap'
    | '/prototype/slides'
    | '/prototype/sources-web'
    | '/settings/connection'
    | '/notebooks/'
    | '/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HomeRoute: typeof HomeRoute
  LoginRoute: typeof LoginRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  NotebooksNotebookIdRoute: typeof NotebooksNotebookIdRoute
  PrototypeFlashcardsRoute: typeof PrototypeFlashcardsRoute
  PrototypeQuizRoute: typeof PrototypeQuizRoute
  PrototypeReportRoute: typeof PrototypeReportRoute
  PrototypeRoadmapRoute: typeof PrototypeRoadmapRoute
  PrototypeSlidesRoute: typeof PrototypeSlidesRoute
  PrototypeSourcesWebRoute: typeof PrototypeSourcesWebRoute
  NotebooksIndexRoute: typeof NotebooksIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notebooks/': {
      id: '/notebooks/'
      path: '/notebooks'
      fullPath: '/notebooks/'
      preLoaderRoute: typeof NotebooksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notebooks/$notebookId': {
      id: '/notebooks/$notebookId'
      path: '/notebooks/$notebookId'
      fullPath: '/notebooks/$notebookId'
      preLoaderRoute: typeof NotebooksNotebookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prototype/flashcards': {
      id: '/prototype/flashcards'
      path: '/prototype/flashcards'
      fullPath: '/prototype/flashcards'
      preLoaderRoute: typeof PrototypeFlashcardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prototype/quiz': {
      id: '/prototype/quiz'
      path: '/prototype/quiz'
      fullPath: '/prototype/quiz'
      preLoaderRoute: typeof PrototypeQuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prototype/report': {
      id: '/prototype/report'
      path: '/prototype/report'
      fullPath: '/prototype/report'
      preLoaderRoute: typeof PrototypeReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prototype/roadmap': {
      id: '/prototype/roadmap'
      path: '/prototype/roadmap'
      fullPath: '/prototype/roadmap'
      preLoaderRoute: typeof PrototypeRoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prototype/slides': {
      id: '/prototype/slides'
      path: '/prototype/slides'
      fullPath: '/prototype/slides'
      preLoaderRoute: typeof PrototypeSlidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prototype/sources-web': {
      id: '/prototype/sources-web'
      path: '/prototype/sources-web'
      fullPath: '/prototype/sources-web'
      preLoaderRoute: typeof PrototypeSourcesWebRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/connection': {
      id: '/settings/connection'
      path: '/connection'
      fullPath: '/settings/connection'
      preLoaderRoute: typeof SettingsConnectionRouteImport
      parentRoute: typeof SettingsRoute
    }
  }
}

interface SettingsRouteChildren {
  SettingsConnectionRoute: typeof SettingsConnectionRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsConnectionRoute: SettingsConnectionRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HomeRoute: HomeRoute,
  LoginRoute: LoginRoute,
  SettingsRoute: SettingsRouteWithChildren,
  NotebooksNotebookIdRoute: NotebooksNotebookIdRoute,
  PrototypeFlashcardsRoute: PrototypeFlashcardsRoute,
  PrototypeQuizRoute: PrototypeQuizRoute,
  PrototypeReportRoute: PrototypeReportRoute,
  PrototypeRoadmapRoute: PrototypeRoadmapRoute,
  PrototypeSlidesRoute: PrototypeSlidesRoute,
  PrototypeSourcesWebRoute: PrototypeSourcesWebRoute,
  NotebooksIndexRoute: NotebooksIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
